[versions]
androidx-core = "1.10.1"
androidx-appcompat = "1.6.1"
material = "1.9.0"
androidx-activity = "1.7.2"
androidx-constraintlayout = "2.1.4"
junit = "4.13.2"
androidx-junit = "1.1.5"
androidx-espresso = "3.5.1"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso" }

[plugins]
android-application = { id = "com.android.application", version = "8.1.0" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version = "1.9.0" }